title: "My Span cat project"
description: "Train a spancat model on the `dataset` defined in `project.yml`"
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  config: "config_trf" # config_tok2vec, config_trf
  dataset: "mitrea_ttack" # healthsea, toxic, genia
  suggester: "span_finder" # ngram, span_finder

  train: "train"
  dev: "dev"
  spans_key: "sc"

  gpu_id: 0
  eval_split: 0.25

  spancat_model: "training/spancat/${vars.dataset}/${vars.config}_${vars.suggester}/model-best"

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "training", "configs", "scripts", "data", "metrics"]

# Assets that should be downloaded or available in the directory. We're shipping
# them with the project, so they won't have to be downloaded. But the
# 'project assets' command still lets you verify that all required files are available.
assets:
  - dest: "assets/data.csv"
    description: "Annotations from the Healthsea dataset"
    url: ""

# Workflows are sequences of commands (see below) executed in order. You can
# run them via "spacy project run [workflow]". If a commands's inputs/outputs
# haven't changed, it won't be re-run.
workflows:
  preprocess:
    - preprocess_data
  spancat:
    - train_spancat
    - evaluate_spancat

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "install"
    help: "Install requirements"
    script:
      - "pip install -r requirements.txt"

  - name: "preprocess_data"
    help: "Format my data annotations into .spaCy training format"
    script:
      - "python scripts/preprocessing/preprocess.py assets/data.csv data/${vars.dataset}_${vars.train}.spacy data/${vars.dataset}_${vars.dev}.spacy ${vars.eval_split} ${vars.spans_key}"
    deps:
      - "assets/data.csv"
      - "scripts/preprocessing/preprocess.py"
    outputs:
      - "data/${vars.dataset}_${vars.train}.spacy"
      - "data/${vars.dataset}_${vars.dev}.spacy"


  - name: "train_spancat"
    help: "Train a spancat model on the `dataset` defined in `project.yml`"
    script:
      - "python -m spacy train configs/${vars.suggester}/${vars.config}.cfg --output training/spancat/${vars.dataset}/${vars.config}_${vars.suggester}/ --paths.train data/${vars.dataset}_${vars.train}.spacy --paths.dev data/${vars.dataset}_${vars.dev}.spacy --gpu-id ${vars.gpu_id}"
    deps:
      - "configs/${vars.suggester}/${vars.config}.cfg"
      - "data/${vars.dataset}_${vars.train}.spacy"
      - "data/${vars.dataset}_${vars.dev}.spacy"
    outputs:
      - "${vars.spancat_model}"

  - name: "evaluate_spancat"
    help: "Evaluate a trained spancat model  on the `dataset` defined in `project.yml`"
    script:
      - "python -m spacy evaluate ${vars.spancat_model} data/${vars.dataset}_${vars.dev}.spacy --output metrics/spancat_${vars.dataset}_${vars.config}_${vars.suggester}.json --gpu-id ${vars.gpu_id}"
      - "python scripts/suggester_evaluation.py ${vars.spans_key} ${vars.spancat_model} data/${vars.dataset}_${vars.dev}.spacy"
    deps:
      - "${vars.spancat_model}"
      - "data/${vars.dataset}_${vars.dev}.spacy"
    outputs:
      - metrics/spancat_${vars.dataset}_${vars.config}_${vars.suggester}.json

  - name: "reset"
    help: "Reset the project to its original state and delete all training process"
    script:
      - "python scripts/reset.py training"
      - "python scripts/reset.py metrics"
      - "python scripts/reset.py assets"
      - "python scripts/reset.py data"